<?php

/**
 *  Implements hook_menu().
 */
function bt_blog_menu() {
  $items = array();

  $items['blog'] = array(
    'title' => 'Blog',
    'description' => 'List of blogs',
    'page callback' => 'bt_blog_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Lists all blogs with pager.
 */
function bt_blog_list() {
  // select image (image style), title, body (trimmed), tags, created date
  $sql  = <<<SQL
    SELECT n.nid, n.title, n.created,
      b.body_value as body,
      ttd.name as tags,
      i.field_blog_image_fid as image,
      fm.uri as uri
    FROM {node} n
      JOIN {field_data_body} b ON n.nid = b.entity_id AND b.bundle = 'blog'
      JOIN {field_data_field_blog_image} i ON n.nid = i.entity_id AND i.bundle = 'blog'
      JOIN {file_managed} fm ON i.field_blog_image_fid = fm.fid
      JOIN {taxonomy_index} ti ON n.nid = ti.nid
      JOIN {taxonomy_term_data} ttd ON ti.tid = ttd.tid
    WHERE
      n.type = 'blog'
    ORDER BY n.created
SQL;

  $blogs = array();
  $result = db_query($sql);
  $image_style_settings = array('style_name' => 'blog_thumbnail_image');
  foreach ($result as $row) {
    if (isset($blogs[$row->nid])) {
      $blogs[$row->nid]['tags'][] = $row->tags;
    }
    else {
      $blogs[$row->nid] = (array) $row;
      $image_style_settings['path'] = $row->uri;
      $blogs[$row->nid]['image_style'] = theme('image_style', $image_style_settings);
      $blogs[$row->nid]['tags'] = array();
      $blogs[$row->nid]['tags'][] = $row->tags;
      $blogs[$row->nid]['url'] = drupal_get_path_alias('node/' . $row->nid);
      $blogs[$row->nid]['display_date'] = date('M d Y', $row->created);
    }
  }

  drupal_add_css(drupal_get_path('module', 'bt_blog') . '/css/bt_blog.css');
  return theme('bt_blog_list', array('blogs' => $blogs));
}

/**
 *  Implements hook_theme().
 */
function bt_blog_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['bt_blog_list'] = array(
    'variables' => array('blogs' => NULL),
    'template' => 'blogs',
    'path' => drupal_get_path('module', 'bt_blog') . '/templates',
  );

  return $items;
}
