<?php

/**
 * Hold all the core related customizations.
 */

/**
 *  Implements hook_preprocess_HOOK().
 */
function bt_core_preprocess_page(&$variables) {
  // Get a listing of all terms in Tag vocabulary.
  $vocab = taxonomy_vocabulary_machine_name_load('tags');
  $sql  = "SELECT t.tid, COUNT(t.tid) AS used FROM {taxonomy_term_data} t ";
  $sql .= "LEFT JOIN {taxonomy_index} ti ON t.tid = ti.tid ";
  $sql .= "WHERE t.vid = :vid ";
  $sql .= "GROUP BY t.tid";
  $result = db_query($sql, array(':vid' => $vocab->vid));
  $terms = array();
  foreach ($result as $row) {
    $term = taxonomy_term_load($row->tid);
    $terms[$term->tid]['name'] = $term->name;
    $terms[$term->tid]['used'] = $row->used;
  }
  $var = '';
}